void convert_int_to_char_array(unsigned char * buffer,int number);
int int_length(int number);
int collect_hash_output(unsigned char* buffer,int ring_size);
int compute_sha1_hash(int not_hashed,int ring_size);
int compute_sha1_hash(char * not_hashed,int ring_size);
struct command * parse_the_command(char * buffer);
int search_in_a_vector_of_files(std::vector<std::pair<int,int>> files,int key);
void forward_message(char *message ,char * hostname, int port);
char * wait_response_initial_node(int port);
void print_node_files(std::vector<std::pair<int,int>>);
